In [104]:
import pandas as pd
import sys
df = pd.read_csv('../data/cereal.csv')
df.head(15)
pd.options.display.max_rows = 10

In [114]:
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,Cold,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,Cold,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,Cold,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,Cold,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,Cold,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,Cold,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,Cold,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,Cold,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,Cold,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,Cold,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

We can use the same format before but now since our rows are named with numbers we no longer need to express the row names in "quotations". So now we would use row names without quotations. 

`df.loc[ row-name-start : row-name-end , "column name start" : "column name end"]`

Let's give our past example a shot. We again want rows "Apple Cinnamon Cheerios" to "Cap'n'Crunch" with all the columns but now the indices are named with numbers.

In [116]:
df.loc[ 5: 10 ]

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
5,Apple Cinnamon Cheerios,G,Cold,110,2,2,180,1.5,10.5,10,70,25,1,1.00,0.75,29.509541
6,Apple Jacks,K,Cold,110,2,0,125,1.0,11.0,14,30,25,2,1.00,1.00,33.174094
7,Basic 4,G,Cold,130,3,2,210,2.0,18.0,8,100,25,3,1.33,0.75,37.038562
8,Bran Chex,R,Cold,90,2,1,200,4.0,15.0,6,125,25,1,1.00,0.67,49.120253
9,Bran Flakes,P,Cold,90,3,0,210,5.0,13.0,5,190,25,3,1.00,0.67,53.313813
10,Cap'n'Crunch,Q,Cold,120,1,2,220,0.0,12.0,12,35,25,2,1.00,0.75,18.042851

What if we wanted only certain columns again too? Note that now `name` is a column now.

In [117]:
df.loc[ 5: 10, "calories" : "fiber"]

    calories  protein  fat  sodium  fiber
5        110        2    2     180    1.5
6        110        2    0     125    1.0
7        130        3    2     210    2.0
8         90        2    1     200    4.0
9         90        3    0     210    5.0
10       120        1    2     220    0.0

The sliced dataframe no longer has `name` in it so we would have to include it in our slice. In the next slide deck we will talk about selecting specific columns and rows that are not consecutive.

In [118]:
df.loc[ 5: 10, "name" : "fiber"]

                       name mfr  type  calories  protein  fat  sodium  fiber
5   Apple Cinnamon Cheerios   G  Cold       110        2    2     180    1.5
6               Apple Jacks   K  Cold       110        2    0     125    1.0
7                   Basic 4   G  Cold       130        3    2     210    2.0
8                 Bran Chex   R  Cold        90        2    1     200    4.0
9               Bran Flakes   P  Cold        90        3    0     210    5.0
10             Cap'n'Crunch   Q  Cold       120        1    2     220    0.0

In [110]:
df.loc[["Wheaties", "Trix", "Clusters"], ['type', 'rating', 'sugars']]

KeyError: KeyError("None of [Index(['Wheaties', 'Trix', 'Clusters'], dtype='object')] are in the [index]",)

In [ ]:
df.iloc[]

In [ ]:
print(df.shape)

In [ ]:
df.length

In [ ]:
pandas_spec = importlib.util.find_spec("pandas") 
found = pandas_spec is not None

In [2]:
import importlib

In [ ]:
found

In [ ]:
pandas_spec

In [8]:
if "pandas" not in sys.modules:
    print('You have not imported the {} module'.format("pandas"))